import os
import sys

print('This script installs every package individually.')
print('Pipenv has been used - Pipfile.lock file is submitted as well.')
print('\n')

print('Installing packages..')
print('\n')
os.system('python3 -m pip install --user -r requirements.txt')

if sys.platform.startswith('win'):
    os.system('python3 -m pip install --user pywin32')
print('\n')
print('.. Done')

# Uncomment below to install packages one by one -------------------------------

# print('Installing packages one by one..')
# print('\n')
# if sys.platform.startswith('win'):
#     os.system('python3 -m pip install --user backcall==0.1.0')
# os.system('python3 -m pip install --user backcall==0.1.0')
# os.system('python3 -m pip install --user certifi==2019.3.9')
# os.system('python3 -m pip install --user chardet==3.0.4')
# os.system('python3 -m pip install --user deap==1.2.2')
# os.system('python3 -m pip install --user decorator==4.4.0')
# os.system('python3 -m pip install --user idna==2.8')
# os.system('python3 -m pip install --user ipdb==0.11')
# os.system('python3 -m pip install --user ipython-genutils==0.2.0')
# os.system('python3 -m pip install --user ipython==7.3.0')
# os.system('python3 -m pip install --user jedi==0.13.3')
# os.system('python3 -m pip install --user lxml==4.3.2')
# os.system('python3 -m pip install --user lz4==2.1.6')
# os.system('python3 -m pip install --user numpy==1.16.2')
# os.system('python3 -m pip install --user pandas==0.24.1')
# os.system('python3 -m pip install --user parso==0.4.0')
# os.system('python3 -m pip install --user pexpect==4.7.0')
# os.system('python3 -m pip install --user pickleshare==0.7.5')
# os.system('python3 -m pip install --user prompt-toolkit==2.0.9')
# os.system('python3 -m pip install --user psutil==5.6.1')
# os.system('python3 -m pip install --user ptyprocess==0.6.0')
# os.system('python3 -m pip install --user pygments==2.3.1')
# os.system('python3 -m pip install --user python-dateutil==2.8.0')
# os.system('python3 -m pip install --user pytz==2019.1')
# os.system('python3 -m pip install --user requests==2.21.0')
# os.system('python3 -m pip install --user scikit-learn==0.20.3')
# os.system('python3 -m pip install --user scipy==1.2.1')
# os.system('python3 -m pip install --user six==1.12.0')
# os.system('python3 -m pip install --user sklearn==0.0')
# os.system('python3 -m pip install --user stopit==1.1.2')
# os.system('python3 -m pip install --user tpot==0.10.0')
# os.system('python3 -m pip install --user tqdm==4.31.1')
# os.system('python3 -m pip install --user traitlets==4.3.2')
# os.system('python3 -m pip install --user update-checker==0.16')
# os.system('python3 -m pip install --user urllib3==1.24.1')
# os.system('python3 -m pip install --user wcwidth==0.1.7')
# os.system('python3 -m pip install --user xgboost==0.82')
# print('\n')
# print('.. Done')


# Uncomment below to use pipenv ------------------------------------------------

# print('--------------------------------')
# print('Installing pipenv..')
# print('\n')
# os.system('pip3 install --user pipenv')
# os.system('echo "PATH=$HOME/.local/bin:$PATH" >> ~/.bashrc')
# # os.system('source ~/.bashrc')
# print('\n')
# print('.. Done')
#
# print('--------------------------------')
# print('Setting up python environment with pipenv..')
# print('\n')
# os.system('$HOME/.local/bin/pipenv install')
# print('\n')
# print('.. Done')
#
# print('--------------------------------')
# print('Running pipenv shell - script could be run using python main_psgx.py')
# print('Otherwise, exit pipenv shell and run ~/.local/bin/pipenv run python main_psgx.py')
# print('\n')
# print('\n')
# os.system('$HOME/.local/bin/pipenv shell')
